name: "Push Docker Image to Registry"
description: "Push a Docker image to a container registry"
author: "Krypton - Vina Sundar"

inputs:
  image-name:
    description: "Docker image name (e.g., my-organization/my-app)"
    required: true
  image-tag:
    description: "Docker image tag"
    required: true
  registry-url:
    description: "Container registry URL"
    required: false
    default: "registry.gitlab.com"
  registry-token:
    description: "Personal Access Token (PAT) for registry authentication"
    required: true
  registry-username:
    description: "Username for registry authentication"
    required: true
  registry-source:
    description: "source location of the registry"
    required: false
    default: "krypton.images"
  push-latest:
    description: "Push latest image to registry"
    required: false
    default: "true"

outputs:
  image-ref:
    description: "Full image reference pushed to registry (registry/name:tag)"
    value: ${{ steps.set-output.outputs.image-ref }}

runs:
  using: "composite"
  steps:
    - name: Log in to Container Registry
      shell: bash
      run: |
        docker login ${{ inputs.registry-url }} -u ${{ inputs.registry-username }} -p ${{ inputs.registry-token }}

    - name: Tag image for registry
      shell: bash
      run: |
        docker tag ${{ inputs.image-name }}:${{ inputs.image-tag }} ${{ inputs.registry-url }}/${{ inputs.registry-username }}/${{ inputs.registry-source }}:${{ inputs.image-tag }}

    - name: Tag image as latest
      if: ${{ inputs.push-latest == 'true' }}
      shell: bash
      run: |
        docker tag ${{ inputs.image-name }}:${{ inputs.image-tag }} ${{ inputs.registry-url }}/${{ inputs.registry-username }}/${{ inputs.registry-source }}:latest

    - name: Push image to registry
      shell: bash
      run: |
        docker push ${{ inputs.registry-url }}/${{ inputs.registry-username }}/${{ inputs.registry-source }}:${{ inputs.image-tag }}

    - name: Push latest image to registry
      if: ${{ inputs.push-latest == 'true' }}
      shell: bash
      run: |
        docker push ${{ inputs.registry-url }}/${{ inputs.registry-username }}/${{ inputs.registry-source }}:latest

    - name: Set output
      id: set-output
      shell: bash
      run: |
        echo "image-ref=${{ inputs.registry-url }}/${{ inputs.registry-username }}/${{ inputs.registry-source }}:${{ inputs.image-tag }}" >> $GITHUB_OUTPUT

    - name: Log out from Container Registry
      shell: bash
      if: always()
      run: |
        docker logout ${{ inputs.registry-url }}
