name: 'Build and Scan Docker Image'
description: 'Build a Docker image and scan it for vulnerabilities using Trivy'
author: 'Your Name'

inputs:
  image-name:
    description: 'Docker image name (e.g., docker.io/my-organization/my-app)'
    required: true
  image-tag:
    description: 'Docker image tag'
    required: true
  dockerfile-path:
    description: 'Path to Dockerfile'
    required: false
    default: '.'
  trivy-severity:
    description: 'Severities to scan for (comma-separated)'
    required: false
    default: 'CRITICAL,HIGH'
  trivy-exit-code:
    description: 'Exit code when vulnerabilities are found (0 = do not fail, 1 = fail on vulnerabilities)'
    required: false
    default: '1'
  continue-on-error:
    description: 'Continue workflow even if vulnerabilities are found'
    required: false
    default: 'false'
  trivy-ignore-unfixed:
    description: 'Ignore unfixed vulnerabilities'
    required: false
    default: 'true'

outputs:
  image-ref:
    description: 'Full image reference (name:tag)'
    value: ${{ steps.set-output.outputs.image-ref }}

runs:
  using: 'composite'
  steps:
    - name: Build Docker image
      shell: bash
      run: |
        docker build -t ${{ inputs.image-name }}:${{ inputs.image-tag }} ${{ inputs.dockerfile-path }}
    
    - name: Set output
      id: set-output
      shell: bash
      run: |
        echo "image-ref=${{ inputs.image-name }}:${{ inputs.image-tag }}" >> $GITHUB_OUTPUT
    
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@0.33.1
      continue-on-error: ${{ inputs.continue-on-error == 'true' }}
      with:
        image-ref: '${{ inputs.image-name }}:${{ inputs.image-tag }}'
        format: 'table'
        exit-code: ${{ inputs.trivy-exit-code }}
        ignore-unfixed: ${{ inputs.trivy-ignore-unfixed }}
        vuln-type: 'os,library'
        severity: ${{ inputs.trivy-severity }}